steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/winged-plate-426209-c8/my-repo/my-app:nginx', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/winged-plate-426209-c8/my-repo/my-app:nginx']

images:
- 'us-central1-docker.pkg.dev/winged-plate-426209-c8/my-repo/my-app:nginx'
options:
  logging: 'CLOUD_LOGGING_ONLY'
