steps:
  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/winged-plate-426209-c8/frontend:$COMMIT_SHA', './frontend']

  # Push frontend Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/winged-plate-426209-c8/frontend:$COMMIT_SHA']

images:
  - 'gcr.io/winged-plate-426209-c8/frontend:$COMMIT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY'
